const categories = [
    "Technology",
    "Health & Wellness",
    "Travel",
    "Food & Cooking",
    "Fashion & Beauty",
    "Finance & Money",
    "Home & Decor",
    "Parenting & Family",
    "Education & Learning",
    "Entertainment",
    "Sports & Fitness",
    "Lifestyle",
    "Business & Entrepreneurship",
    "Arts & Culture",
    "Science & Environment",
    "DIY & Crafts",
    "Books & Literature",
    "Personal Development",
    "Relationships & Dating",
    "Spirituality & Religion"
];
const tags = [
    "Tech",
    "Health",
    "Travel",
    "Food",
    "Fashion",
    "Finance",
    "HomeDecor",
    "Parenting",
    "Education",
    "Entertainment",
    "Sports",
    "Lifestyle",
    "Business",
    "Art",
    "Science",
    "DIY",
    "Books",
    "Development",
    "Relationships",
    "Spirituality",
    "Culture",
    "Environment",
    "Crafts",
    "Literature",
    "Dating",
    "Religion"
];
  
module.exports = {categories,tags}
  